version: "3"
services:
  node1:
    build:
      context: .
      dockerfile: ./cepa_routing/cepa_routing.Dockerfile
    image: cepa-router
    networks:
      demo_net:
        ipv4_address: 192.168.1.11
  node2:
    image: cepa-router
    networks:
      demo_net:
        ipv4_address: 192.168.1.12
  node3:
    image: cepa-router
    networks:
      demo_net:
        ipv4_address: 192.168.1.13
networks:
  demo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
