version: "3"
services:
  index:
    build:
      context: .
      dockerfile: ./cepa_index/cepa_index.Dockerfile
    image: cepa-index
    ports:
      - 8000:8000
  node1:
    build:
      context: .
      dockerfile: ./cepa_routing/cepa_routing.Dockerfile
    image: cepa-router
    depends_on:
      - index
  node2:
    depends_on:
      - index
    image: cepa-router
  node3:
    depends_on:
      - index
    image: cepa-router
