#!/bin/python

import requests
import sys

if len(sys.argv) != 3:
    print("Usage: add HOST PUB_KEY")
    exit(1)

r = requests.post('https://cepa.ech0.ch:443', json={
  "host": "{}".format(sys.argv[1]),
  "pub_key": "{}".format(sys.argv[2]),
})

print(f"Status Code: {r.status_code}, Response: {r.content.decode('utf-8')}")
