#!/bin/python

import requests
import json

r = requests.get('https://cepa.ech0.ch:443/', verify=True)

print(f"Status Code: {r.status_code}")
print("Response:")
print(json.dumps(json.loads(r.content.decode("utf-8")), indent=2))
